openapi: 3.0.1
info:
  title: API de Estados Brasileiros
  description: Esta API foi desenvolvida em Spring Boot e permite ao usuário criar, recuperar, atualizar e remover dados de Estados brasileiros em um banco de dados H2 local.
  version: 0.0.1
  termsOfService: https://github.com/pedro-as/compass-sprint3/blob/main/README.md
  contact:
    name: API support
    email: amorimp@pm.me
  license:
    name: GPLv3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
externalDocs:
  description: Source code
  url: https://github.com/pedro-as/compass-sprint3/
servers:
  - url: localhost:8080
    description: API de testes
paths:
  /estados:
    get:
      summary: Lista todos os Estados
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estados"
    post:
      summary: Cadastra um novo Estado
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Estado"
      responses:
        '201':
          description: Estado cadastrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
  /estados/{id}:
    parameters:
      - name: id
        in: path
        schema:
          type: integer
        required: true
    get:
      summary: Recupera um Estado com base no ID
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        '404':
          description: ID não encontrado
          content:
            application/json:
              example: Not Found
    put:
      summary: Atualiza um Estado com base no ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Estado"
      responses:
        '200':
          description: Estado atualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        '404':
          description: ID não encontrado
          content:
            application/json:
              example: Not Found
    delete:
      summary: Remove um Estado com base no ID
      responses:
        '200':
          description: Estado removido
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Estado"
        '404':
          description: ID não encontrado
          content:
            application/json:
              example: Not Found
components:
  schemas:
    Estado:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        regiao:
          type: string
        populacao:
          type: integer
          format: int64
        capital:
          type: string
        area:
          type: number
          format: double
      required:
      - nome
      - regiao
      example:
        id: 13
        nome: "Minas Gerais"
        regiao: "Sudeste"
        populacao: 21411923
        capital: "Belo Horizonte"
        area: 586513.993
    Estados:
      type: array
      items:
        $ref: "#/components/schemas/Estado"